### ISSUE TITLE
request: shortcut optional

### ISSUE THREAD

**Issue by javl** [Droggol/OdooDebug#12]
The keyboard shortcut for my 1password extension didn't work anymore and it was driving me crazy until I checked my browser's logs and noticed it was reloading the page with ?debug=1 added to the URL. Turns out your extension is using the same ```ctrl + period``` shortcut as 1password.

Maybe it would be possible to make it so that you can disable or change the shortcut? (to me the 1password shortcut is more important, and I don't mind just clicking the monkey icon)

**Comment by jat-odoo** [comment]
@javl You can change extensions shortcut.

![image](https://user-images.githubusercontent.com/7599689/158022331-7a4351b5-514d-4c37-9d71-9b4b405e7399.png)

**Comment by javl** [comment]
Sorry, I never knew there was a global settings page for shortcuts! Thank you.
