### ISSUE TITLE
chrome error Uncaught ReferenceError: browser is not defined

### ISSUE THREAD

**Issue by t-np** [Droggol/OdooDebug#8]
currentBrowser = browser;
contentScript.js:5 Uncaught ReferenceError: browser is not defined

https://github.com/Droggol/OdooDebug/commit/5b13e50a200089afb6df73f829248de88c8e8c83#r37
816962 generates an error on chrome Version 80.0.3987.132

i seen the error for weeks but never looked into it and thought it comes somewhere from odoo but chrome just does not have a browser variable.

**Comment by jat-odoo** [comment]
@t-np Thanks for reporting issue. We will try to fix it ASAP.

**Comment by jat-odoo** [comment]
Fixed at https://github.com/Droggol/OdooDebug/pull/9
